/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*

#include <stdlib.h>
#include "stm32f303xc.h"

#include "timer.h"

// ════════════════════════════════════════════════════════
// TEST CODE — put this in main.c
// ════════════════════════════════════════════════════════

// toggle LED on PE8 every time periodic fires
void test_periodic(void *args) {
    GPIOE->ODR ^= (1 << 8);
}

int main(void) {
    // enable GPIOE clock and set PE8 as output
    RCC->AHBENR  |= RCC_AHBENR_GPIOEEN;
    GPIOE->MODER |= (1 << (8 * 2));

    // periodic every 500ms, no oneshot for now
    timer_init(500, test_periodic, 0, NULL);

    while(1) {
        // nothing here — LED toggles in background
    }
}

*/

#include "stm32f303xc.h"
#include "timer.h"
#include "pwm.h"
#include <stddef.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void setup_GPIO_for_test(void){
	// Set mode
	// Use GPIOA
	RCC->AHBENR |= RCC_AHBENR_GPIODEN | RCC_AHBENR_GPIOEEN;
	// set PE8 as output
    GPIOE->MODER |= (GPIO_MODER_MODER8_0);
    GPIOD->MODER |= (GPIO_MODER_MODER6_0);
}

// called when pin goes HIGH
void on_rising_edge(void *args) {
    GPIOE->ODR |= (1 << 8);       // PE8 HIGH
    GPIOD->ODR |= (1 << 6);       // PB6 HIGH
}

// called when pin goes LOW
void on_falling_edge(void *args) {
    GPIOE->ODR &= ~(1 << 8);      // PE8 LOW
    GPIOD->ODR &= ~(1 << 6);      // PB6 LOW
}

int main(void) {
	setup_GPIO_for_test();

    // 20ms period, 1.5ms pulse (centre position)
    pwm_init(20, 2, on_rising_edge, on_falling_edge);

    while(1) {
        // everything runs in background
    }
}
