/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "comm/uart.h"

#include "integration.h"

int main(void)
{

	// TEST FUNCTIONS, COMMENT OR UNCOMMENT THEM, BUT DO NOT DELETE THEM
	// Exercise 1: Digital I/O

	// Exercise 2: Timer Interface

	// Exercise 3: Serial interface
//	testSerial();
	testSerialString();

	// Exercise 4: I2C Sensor Interfacing
	// testGyro();

	// Exercise 5: Integration Task


    /* Loop forever */
	for(;;);
}
