/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f303xc.h"

#include <stdint.h>

#include "comm/uart.h"
#include "sensors/gyro.h"
#include "timer.h"

#include "integration.h"

void SystemInit(void) {
	#if (__FPU_PRESENT == 1) && (__FPU_USED == 1)
	  SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));  /* set CP10 and CP11 Full Access */
	#endif
}

int main(void)
{

	// TEST FUNCTIONS, COMMENT OR UNCOMMENT THEM, BUT DO NOT DELETE THEM
	// Exercise 1: Digital I/O

	// Exercise 2: Timer Interface

	// Exercise 3: Serial interface
	// testSerial();
	// testSerialString();

	// Exercise 4: I2C Sensor Interfacing
	testGyro();

	// Exercise 5: Integration Task


    /* Loop forever */
	for(;;);
}
